<?xml version="1.0" encoding="utf-8"?>
<Database Name="cms_database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=VANNA-PC;Initial Catalog=cms_database;Persist Security Info=True;User ID=sa" SettingsObjectName="Clinic_Management_System.My.MySettings" SettingsPropertyName="cms_databaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category_Items" Member="Category_Items">
    <Type Name="Category_Item">
      <Column Name="Item_ID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Category_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_Description" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Check_Items" Member="Check_Items">
    <Type Name="Check_Item">
      <Column Name="Item_ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Item_Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.City_Provinces" Member="City_Provinces">
    <Type Name="City_Province">
      <Column Name="Province_Code" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Province_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Consult_Categories" Member="Consult_Categories">
    <Type Name="Consult_Category">
      <Column Name="Category_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Disease_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Category_Description" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Consult_Diseases" Member="Consult_Diseases">
    <Type Name="Consult_Disease">
      <Column Name="Disease_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Disease_Name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Consultation_Results" Member="Consultation_Results">
    <Type Name="Consultation_Result">
      <Column Name="Result_ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PConsult_No" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Item_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Is_Yes" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Result_Text" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patients" Member="Patients">
    <Type Name="Patient">
      <Column Name="Patient_ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Full_Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Identification_Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="City_Province" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Birth_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Is_Valid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.tblConsultType" Member="tblConsultTypes">
    <Type Name="tblConsultType">
      <Column Name="consulttypeid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="consulttypename" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Consultations" Member="Consultations">
    <Type Name="Consultation">
      <Column Name="Consult_No" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Patient_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Check_Details" Member="Check_Details">
    <Type Name="Check_Detail">
      <Column Name="Check_No" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="prescriptionid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Patient_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Check_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="User_Create" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Consultation_Details" Member="Consultation_Details">
    <Type Name="Consultation_Detail">
      <Column Name="PConsult_No" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="prescriptionid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Patient_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Disease_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Consult_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="User_Create" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Check_Results" Member="Check_Results">
    <Type Name="Check_Result">
      <Column Name="Result_ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Check_No" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Item_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Checked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>